# Generated by Django 4.0.4 on 2024-04-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
